# Generated by Django 5.2.5 on 2026-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non Vegetarian')], default='veg', max_length=10),
        ),
    ]
